from marc_to_folio.alabama_mapper import AlabamaMapper
from marc_to_folio.five_collages_mapper import FiveCollagesMapper
from marc_to_folio.chalmers_mapper import ChalmersMapper
from marc_to_folio.default_mapper import DefaultMapper