# readthedocs.yml
version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
